# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/bot ./cmd/bot"
  bin = "tmp/bot"
  full_bin = "tmp/bot"
  include_ext = ["go"]
  exclude_dir = ["tmp", "vendor"]

[color]
  main = "cyan"
  watcher = "yellow"
