services:
  db:
    image: postgres:15-alpine
    container_name: tg_template_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: tg_template_bot
    env_file:
      - .env
    command: ["sh", "-c", "./wait-for-db.sh ${DB_HOST}:${DB_PORT} ./bot"]
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}

volumes:
  pgdata:
