version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: tg_template_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  bot:
    image: tg_bot
    container_name: tg_bot
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped

volumes:
  pgdata:
