apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-template-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-template-db
  template:
    metadata:
      labels:
        app: tg-template-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: tg-db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tg-db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: tgdb
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pgdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: tg-template-db
  ports:
  - port: 5432
    targetPort: 5432
